#!/usr/bin/env sage -python
"""
Stage 16: CM split-prime ideal-class fibers + norm-one ratios + centered polydisc.

This is the most proof-aligned finite engine so far.

Motivation
----------
Earlier stages used:
    - explicit Gaussian split-prime fibers in Q(i);
    - principal products of split prime ideals in Q(zeta_m);
    - same-norm fibers found by coefficient search.

The paper's asymptotic mechanism is stronger:
    many products of split prime ideals are forced, by class-group pigeonholing,
    to lie in the same ideal class. Ratios of ideals in the same class are
    principal. Their generators produce algebraic elements whose CM quotients
    have relative norm 1.

Stage 16 implements this finite analogue:

    K = Q(zeta_m), a CM field.
    Pick rational primes p == 1 mod m, so they split completely in K.
    Pair prime ideals above p under CM conjugation.
    Enumerate choices of one ideal from each conjugate pair.
    Cluster these product ideals by ideal class using principal-ratio tests.
    For a large class-fiber:
        I / I0 = (alpha)
        u = alpha / c(alpha)
    Then:
        u*c(u) = 1 exactly.
    Use selected u's as unit translations in every complex embedding.
    Build centered subset sums:
        sum_j (eps_j - 1/2) sigma(u_j)
    Keep points in a Minkowski product-of-discs:
        max_sigma |...| <= R
    Project to sigma_1(K) ~= C and count unit-distance edges.

Default file policy:
    - summary CSVs only
    - no huge points/edges/translations files unless --save-details
    - no PNG unless --plot-best
"""

from __future__ import annotations

import argparse
import csv
import math
import random
from pathlib import Path

import numpy as np

from sage.all import CyclotomicField, CC  # type: ignore


# ---------------------------------------------------------------------
# Basic utilities
# ---------------------------------------------------------------------

def write_csv(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            out = {}
            for key in fieldnames:
                value = row.get(key, "")
                if isinstance(value, (list, tuple)):
                    value = " ".join(str(x) for x in value)
                out[key] = value
            writer.writerow(out)


def exact_key(z) -> str:
    return str(z)


def is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    d = 3
    while d * d <= n:
        if n % d == 0:
            return False
        d += 2
    return True


def primes_split_completely_in_cyclotomic(m: int, count: int) -> list[int]:
    """In Q(zeta_m), unramified rational p splits completely iff p ≡ 1 mod m."""
    primes = []
    n = 2
    while len(primes) < count:
        if n % m == 1 and is_prime(n):
            primes.append(n)
        n += 1
    return primes


def near_square_grid_unit_edges(n: int) -> tuple[int, int, int]:
    rows = int(math.floor(math.sqrt(n)))
    cols = int(math.ceil(n / rows))
    occupied = {(idx // cols, idx % cols) for idx in range(n)}
    edges = 0
    for r, c in occupied:
        if (r, c + 1) in occupied:
            edges += 1
        if (r + 1, c) in occupied:
            edges += 1
    return rows, cols, edges


def parse_optional_float_list(items: list[str]) -> list[float | None]:
    out = []
    for item in items:
        if item.lower() in {"none", "null", "nan"}:
            out.append(None)
        else:
            out.append(float(item))
    return out


# ---------------------------------------------------------------------
# CM field / ideals
# ---------------------------------------------------------------------

def make_cm_conjugation(K):
    zeta = K.gen()
    return K.hom([zeta ** (-1)], K)


def conjugate_ideal(K, conj, I):
    return K.ideal([conj(g) for g in I.gens()])


def pair_conjugate_prime_ideals(K, conj, prime_ideals):
    unused = list(prime_ideals)
    pairs = []

    while unused:
        P = unused.pop(0)
        cP = conjugate_ideal(K, conj, P)

        found_idx = None
        for i, Q in enumerate(unused):
            if Q == cP:
                found_idx = i
                break

        if found_idx is None:
            # Fixed by conjugation or Sage comparison failed; not useful here.
            continue

        Q = unused.pop(found_idx)
        pairs.append((P, Q))

    return pairs


def ideal_generated_by(K, g):
    """Try to build the principal fractional ideal generated by g."""
    for method_name in ["ideal", "fractional_ideal"]:
        try:
            return getattr(K, method_name)(g)
        except Exception:
            continue
    return None


def quotient_ideal(I, J):
    """Return I * J^-1, Sage-version-tolerant."""
    try:
        return I * J.inverse()
    except Exception:
        try:
            return I / J
        except Exception:
            return None


def try_principal_generator(K, I):
    """
    Try to obtain a generator g with (g) = I.

    Works for integral ideals in many Sage builds, and attempts fractional ideals
    too. Returns None if Sage cannot prove principality / extract a generator.
    """
    if I is None:
        return None

    try:
        if hasattr(I, "is_principal") and not I.is_principal():
            return None
    except Exception:
        pass

    # Direct principal-generator APIs.
    for method_name in ["principal_generator", "generator"]:
        try:
            g = getattr(I, method_name)()
            J = ideal_generated_by(K, g)
            if J is not None and J == I:
                return g
        except Exception:
            pass

    # Try generators/reduced generators.
    for method_name in ["gens_reduced", "gens"]:
        try:
            gens = list(getattr(I, method_name)())
            for g in gens:
                J = ideal_generated_by(K, g)
                if J is not None and J == I:
                    return g
        except Exception:
            pass

    # Some fractional ideals can be generated by one of their generators only up
    # to denominator normalization; try the principal ideal containment route.
    try:
        gens = list(I.gens())
        if len(gens) == 1:
            return gens[0]
    except Exception:
        pass

    return None


def principal_complex_value(z) -> complex:
    return complex(CC(z))


def principal_angle(z) -> float:
    v = principal_complex_value(z)
    t = math.atan2(v.imag, v.real)
    if t < 0:
        t += 2 * math.pi
    return t


def embedding_values(embeddings, z):
    return [complex(emb(z)) for emb in embeddings]


def build_split_prime_pairs(m: int, split_prime_count: int, verbose: bool):
    K = CyclotomicField(m, "z")
    conj = make_cm_conjugation(K)
    embeddings = K.embeddings(CC)

    primes = primes_split_completely_in_cyclotomic(m, split_prime_count)
    pair_blocks = []
    factor_summary = []

    for p in primes:
        fac = list(K.ideal(p).factor())
        prime_ideals = [P for P, e in fac if e == 1]
        pairs = pair_conjugate_prime_ideals(K, conj, prime_ideals)

        pair_blocks.extend(pairs)

        factor_summary.append(
            {
                "m": m,
                "p": p,
                "prime_ideal_count": len(prime_ideals),
                "conjugate_pair_count": len(pairs),
            }
        )

    if verbose:
        print(f"K = Q(zeta_{m}), degree={K.degree()}")
        print(f"split rational primes: {primes}")
        print(f"conjugate ideal pairs: {len(pair_blocks)}")

    metadata = {
        "m": m,
        "degree": K.degree(),
        "embedding_count": len(embeddings),
        "split_primes": " ".join(str(p) for p in primes),
        "split_prime_count": split_prime_count,
        "conjugate_pair_count": len(pair_blocks),
        "ideal_choices": 1 << len(pair_blocks),
    }

    return K, conj, embeddings, pair_blocks, metadata, factor_summary


def enumerate_product_ideals(K, pair_blocks, max_ideal_choices: int):
    total_pairs = len(pair_blocks)
    total_choices = 1 << total_pairs

    if total_choices > max_ideal_choices:
        raise RuntimeError(
            f"Too many ideal choices: 2^{total_pairs}={total_choices}, "
            f"exceeds --max-ideal-choices={max_ideal_choices}."
        )

    one = K.ideal(1)
    products = []

    for mask in range(total_choices):
        I = one
        for j, (P, Q) in enumerate(pair_blocks):
            I *= Q if ((mask >> j) & 1) else P
        products.append({"mask": mask, "ideal": I})

    return products


# ---------------------------------------------------------------------
# Class-fiber clustering
# ---------------------------------------------------------------------

def cluster_by_principal_ratios(K, products: list[dict], verbose: bool):
    """
    Greedy clustering by ideal class.

    For a product ideal I and a bucket representative I0, test whether I/I0 is
    principal. If yes, I is in the same ideal class and the generator alpha of
    I/I0 is stored.

    This avoids relying on Sage's class-group API, and directly produces the
    principal ratios needed for norm-one translations.
    """
    buckets = []
    ratio_tests = 0
    ratio_successes = 0
    ratio_failures = 0

    for idx, row in enumerate(products):
        I = row["ideal"]
        assigned = False

        for bucket_id, bucket in enumerate(buckets):
            J = quotient_ideal(I, bucket["rep_ideal"])
            ratio_tests += 1
            alpha = try_principal_generator(K, J)

            if alpha is not None:
                ratio_successes += 1
                bucket["members"].append(
                    {
                        "mask": row["mask"],
                        "ideal": I,
                        "alpha": alpha,
                        "bucket_id": bucket_id,
                    }
                )
                assigned = True
                break
            else:
                ratio_failures += 1

        if not assigned:
            bucket_id = len(buckets)
            buckets.append(
                {
                    "bucket_id": bucket_id,
                    "rep_mask": row["mask"],
                    "rep_ideal": I,
                    "members": [
                        {
                            "mask": row["mask"],
                            "ideal": I,
                            "alpha": K(1),
                            "bucket_id": bucket_id,
                        }
                    ],
                }
            )

        if verbose and (idx + 1) % 1000 == 0:
            best = max(len(b["members"]) for b in buckets)
            print(
                f"  clustered {idx+1}/{len(products)} products; "
                f"buckets={len(buckets)} best_bucket={best}"
            )

    bucket_rows = []
    for b in buckets:
        bucket_rows.append(
            {
                "bucket_id": b["bucket_id"],
                "rep_mask": b["rep_mask"],
                "bucket_size": len(b["members"]),
            }
        )

    stats = {
        "class_bucket_count": len(buckets),
        "principal_ratio_tests": ratio_tests,
        "principal_ratio_successes": ratio_successes,
        "principal_ratio_failures": ratio_failures,
        "largest_bucket_size": max((len(b["members"]) for b in buckets), default=0),
    }

    return buckets, bucket_rows, stats


def make_norm_one_translation_rows(K, conj, embeddings, bucket):
    """
    For members in one ideal-class bucket, alpha generates I/I0.
    Build u = alpha / c(alpha), so u*c(u)=1 exactly.
    """
    rows = []
    seen = set()

    for member in bucket["members"]:
        alpha = member["alpha"]
        calpha = conj(alpha)

        if calpha == 0:
            continue

        u = alpha / calpha

        # Exact check.
        try:
            if u * conj(u) != 1:
                continue
        except Exception:
            continue

        # Deduplicate u and -u, because they give the same undirected direction.
        u_key_signed = exact_key(u)
        u_key = min(u_key_signed, exact_key(-u))

        if u_key in seen:
            continue
        seen.add(u_key)

        vals = embedding_values(embeddings, u)
        abs_vals = [abs(v) for v in vals]

        rows.append(
            {
                "u": u,
                "u_key": u_key_signed,
                "mask": member["mask"],
                "angle": principal_angle(u),
                "principal_abs": float(abs_vals[0]),
                "max_abs_all_embeddings": float(max(abs_vals)),
                "embedding_values": vals,
            }
        )

    rows.sort(key=lambda r: r["angle"])
    return rows


# ---------------------------------------------------------------------
# Selection + centered polydisc
# ---------------------------------------------------------------------

def select_spread_by_angle(candidates: list[dict], count: int) -> list[dict]:
    candidates = sorted(candidates, key=lambda r: r["angle"])
    if count >= len(candidates):
        return candidates

    angles = np.array([row["angle"] for row in candidates], dtype=float)
    selected_indices = [0]

    while len(selected_indices) < count:
        best_idx = None
        best_score = -1.0
        for i, angle in enumerate(angles):
            if i in selected_indices:
                continue
            min_dist = math.inf
            for j in selected_indices:
                diff = abs(angle - angles[j])
                diff = min(diff, 2 * math.pi - diff)
                min_dist = min(min_dist, diff)
            if min_dist > best_score:
                best_score = min_dist
                best_idx = i
        assert best_idx is not None
        selected_indices.append(best_idx)

    selected = [candidates[i] for i in selected_indices]
    selected.sort(key=lambda r: r["angle"])
    return selected


def select_random(candidates: list[dict], count: int, rng: random.Random) -> list[dict]:
    if count >= len(candidates):
        return list(candidates)
    selected = rng.sample(candidates, count)
    selected.sort(key=lambda r: r["angle"])
    return selected


def centered_polydisc_points(
    selected: list[dict],
    polydisc_radius: float | None,
    principal_radius: float | None,
    save_details: bool,
):
    """
    Build centered subset sums of norm-one translations:
        sum_j (eps_j - 1/2) u_j.

    Exact dedup key:
        2*sum eps_j u_j - sum u_j.
    """
    r = len(selected)
    raw_total = 1 << r

    U = np.array([row["embedding_values"] for row in selected], dtype=complex)
    u_exact = [row["u"] for row in selected]

    total_numeric = np.sum(U, axis=0)
    total_exact = sum(u_exact)

    point_rows = []
    mask_to_point_id = {}
    exact_to_point_id = {}
    raw_kept = 0
    collisions = 0

    numeric_sums = [None] * raw_total
    exact_sums = [None] * raw_total
    numeric_sums[0] = np.zeros(U.shape[1], dtype=complex)
    exact_sums[0] = 0 * u_exact[0] if u_exact else 0

    for mask in range(raw_total):
        if mask != 0:
            lsb = mask & -mask
            j = lsb.bit_length() - 1
            prev = mask ^ lsb
            numeric_sums[mask] = numeric_sums[prev] + U[j]
            exact_sums[mask] = exact_sums[prev] + u_exact[j]

        centered_values = numeric_sums[mask] - 0.5 * total_numeric
        principal_abs = abs(centered_values[0])
        max_abs = float(np.max(np.abs(centered_values)))

        if polydisc_radius is not None and max_abs > polydisc_radius:
            continue
        if principal_radius is not None and principal_abs > principal_radius:
            continue

        raw_kept += 1

        centered_exact = 2 * exact_sums[mask] - total_exact
        z_key = exact_key(centered_exact)

        if z_key in exact_to_point_id:
            pid = exact_to_point_id[z_key]
            mask_to_point_id[mask] = pid
            collisions += 1
            continue

        pid = len(point_rows)
        exact_to_point_id[z_key] = pid
        mask_to_point_id[mask] = pid

        row = {
            "id": pid,
            "mask": mask,
            "x": float(centered_values[0].real),
            "y": float(centered_values[0].imag),
            "principal_abs": float(principal_abs),
            "max_embedding_abs": float(max_abs),
        }

        if save_details:
            row["exact_centered_key"] = z_key

        point_rows.append(row)

    return point_rows, mask_to_point_id, raw_total, raw_kept, collisions


def count_edges(point_rows, mask_to_point_id, selected_count: int, save_details: bool):
    id_to_point = {row["id"]: row for row in point_rows}
    edge_seen = set()
    edge_rows = []
    loop_collisions = 0

    for mask, source_id in mask_to_point_id.items():
        for j in range(selected_count):
            if (mask >> j) & 1:
                continue

            target_mask = mask | (1 << j)
            target_id = mask_to_point_id.get(target_mask)

            if target_id is None:
                continue

            if source_id == target_id:
                loop_collisions += 1
                continue

            key = (source_id, target_id) if source_id < target_id else (target_id, source_id)
            if key in edge_seen:
                continue
            edge_seen.add(key)

            if save_details:
                p = id_to_point[key[0]]
                q = id_to_point[key[1]]
                dist = math.hypot(q["x"] - p["x"], q["y"] - p["y"])
                edge_rows.append(
                    {
                        "from_id": key[0],
                        "to_id": key[1],
                        "x1": p["x"],
                        "y1": p["y"],
                        "x2": q["x"],
                        "y2": q["y"],
                        "numeric_distance": dist,
                        "changed_generator": j,
                    }
                )

    return len(edge_seen), edge_rows, loop_collisions


def evaluate_selected(
    selected: list[dict],
    bucket_id: int,
    bucket_size: int,
    candidate_translation_count: int,
    selection_method: str,
    selection_attempt: int,
    polydisc_radius: float | None,
    principal_radius: float | None,
    save_details: bool,
):
    point_rows, mask_to_point_id, raw_total, raw_kept, collisions = centered_polydisc_points(
        selected=selected,
        polydisc_radius=polydisc_radius,
        principal_radius=principal_radius,
        save_details=save_details,
    )

    if not point_rows:
        return None, None

    edge_count, edge_rows, loop_collisions = count_edges(
        point_rows=point_rows,
        mask_to_point_id=mask_to_point_id,
        selected_count=len(selected),
        save_details=save_details,
    )

    n = len(point_rows)
    grid_rows, grid_cols, grid_edges = near_square_grid_unit_edges(n)

    max_edge_error = ""
    if edge_rows:
        max_edge_error = max(abs(float(row["numeric_distance"]) - 1.0) for row in edge_rows)

    summary = {
        "bucket_id": bucket_id,
        "bucket_size": bucket_size,
        "candidate_norm_one_translations": candidate_translation_count,
        "selected_translations": len(selected),
        "selection_method": selection_method,
        "selection_attempt": selection_attempt,
        "polydisc_radius": "none" if polydisc_radius is None else polydisc_radius,
        "principal_radius": "none" if principal_radius is None else principal_radius,
        "raw_total_subset_sums": raw_total,
        "raw_kept_subset_sums": raw_kept,
        "distinct_points": n,
        "exact_point_collisions": collisions,
        "edge_loop_collisions": loop_collisions,
        "unit_distance_pairs": edge_count,
        "grid_rows": grid_rows,
        "grid_cols": grid_cols,
        "grid_unit_distance_pairs": grid_edges,
        "ratio_vs_grid": edge_count / grid_edges if grid_edges else 0,
        "avg_unit_neighbors_per_point": 2 * edge_count / n,
        "numeric_max_edge_error": max_edge_error,
    }

    data = {
        "point_rows": point_rows,
        "edge_rows": edge_rows,
        "selected": selected,
    }

    return summary, data


def plot_result(output_png: Path, point_rows, edge_rows, summary, max_plot_edges: int):
    """
    Publication-oriented final plot, v3.

    This version is tuned for the smaller final examples (~4k to ~16k points):
      - larger, more legible points;
      - no inset;
      - right panel shows the full same-size grid directly.
    """
    try:
        import matplotlib.pyplot as plt
        from matplotlib.collections import LineCollection
    except Exception as exc:
        print(f"Plot skipped: {exc}")
        return

    n = int(summary["distinct_points"])
    grid_rows = int(summary["grid_rows"])
    grid_cols = int(summary["grid_cols"])
    grid_edges = int(summary["grid_unit_distance_pairs"])

    xy = np.array([[row["x"], row["y"]] for row in point_rows], dtype=float)
    colors = np.array([row["max_embedding_abs"] for row in point_rows], dtype=float)

    fig, axes = plt.subplots(1, 2, figsize=(18, 8), dpi=300)

    # ------------------------------------------------------------
    # Left panel: CM construction
    # ------------------------------------------------------------
    ax = axes[0]
    plot_edges = edge_rows

    if len(plot_edges) > max_plot_edges:
        idx = np.linspace(0, len(plot_edges) - 1, max_plot_edges).astype(int)
        plot_edges = [plot_edges[int(i)] for i in idx]

    if plot_edges:
        segments = np.array(
            [[[e["x1"], e["y1"]], [e["x2"], e["y2"]]] for e in plot_edges],
            dtype=float,
        )
        ax.add_collection(
            LineCollection(
                segments,
                linewidths=0.18,
                alpha=0.10,
                rasterized=True,
                zorder=1,
            )
        )

    sc = ax.scatter(
        xy[:, 0],
        xy[:, 1],
        c=colors,
        s=1.1,
        alpha=0.82,
        linewidths=0,
        rasterized=True,
        zorder=3,
    )

    cbar = fig.colorbar(sc, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label("max embedding |centered sum|")

    ax.autoscale()
    ax.set_aspect("equal", adjustable="box")
    ax.grid(True, linewidth=0.28, alpha=0.18)
    ax.set_xlabel("Re(centered sigma_1 sum)")
    ax.set_ylabel("Im(centered sigma_1 sum)")
    ax.set_title("CM ideal-class construction")

    ax.text(
        0.02,
        0.98,
        (
            f"bucket size: {summary['bucket_size']:,}
"
            f"norm-one candidates: {summary['candidate_norm_one_translations']:,}
"
            f"distinct points: {n:,}
"
            f"unit-distance pairs: {summary['unit_distance_pairs']:,}
"
            f"ratio vs grid: {summary['ratio_vs_grid']:.2f}x"
        ),
        transform=ax.transAxes,
        va="top",
        bbox=dict(boxstyle="round", alpha=0.86),
        fontsize=10,
    )

    # ------------------------------------------------------------
    # Right panel: near-square grid with the same number of points
    # ------------------------------------------------------------
    ax = axes[1]

    xs = np.arange(n, dtype=np.int64) % grid_cols
    ys = np.arange(n, dtype=np.int64) // grid_cols

    # Draw the full set of unit edges for the grid. At this size it remains readable.
    grid_segments = []
    occupied = {(int(y), int(x)) for x, y in zip(xs, ys)}
    for y, x in occupied:
        if (y, x + 1) in occupied:
            grid_segments.append([[x, y], [x + 1, y]])
        if (y + 1, x) in occupied:
            grid_segments.append([[x, y], [x, y + 1]])

    if grid_segments:
        ax.add_collection(
            LineCollection(
                np.array(grid_segments, dtype=float),
                linewidths=0.18,
                alpha=0.08,
                rasterized=True,
                zorder=1,
            )
        )

    ax.scatter(
        xs,
        ys,
        s=1.1,
        alpha=0.78,
        linewidths=0,
        rasterized=True,
        zorder=3,
    )

    ax.set_xlim(-2, grid_cols + 1)
    ax.set_ylim(-2, grid_rows + 1)
    ax.set_aspect("equal", adjustable="box")
    ax.grid(True, linewidth=0.28, alpha=0.16)
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_title(f"Near-square grid with same n
{grid_rows:,} rows x {grid_cols:,} columns")

    ax.text(
        0.02,
        0.98,
        (
            f"points: {n:,}
"
            f"unit-distance pairs: {grid_edges:,}
"
            f"avg. unit neighbors: {2 * grid_edges / n:.2f}"
        ),
        transform=ax.transAxes,
        va="top",
        bbox=dict(boxstyle="round", alpha=0.86),
        fontsize=10,
    )

    # ------------------------------------------------------------
    # Global title
    # ------------------------------------------------------------
    fig.suptitle(
        "Final 2D visualization: CM split-prime / ideal-class construction vs grid
"
        f"{summary['unit_distance_pairs']:,} vs {grid_edges:,} unit-distance pairs "
        f"({summary['ratio_vs_grid']:.2f}x grid)",
        y=1.02,
        fontsize=15,
    )

    fig.tight_layout()
    fig.savefig(output_png, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--m-values", type=int, nargs="+", default=[16, 20, 24, 28, 32])
    parser.add_argument("--split-prime-counts", type=int, nargs="+", default=[2, 3])
    parser.add_argument("--translation-counts", type=int, nargs="+", default=[12, 14, 16, 18])
    parser.add_argument("--polydisc-radii", type=str, nargs="+", default=["2.5", "3", "3.5", "4", "4.5"])
    parser.add_argument("--principal-radii", type=str, nargs="+", default=["none"])
    parser.add_argument("--selection-methods", type=str, nargs="+", default=["angle"])
    parser.add_argument("--random-attempts", type=int, default=0)
    parser.add_argument("--random-seed", type=int, default=12345)
    parser.add_argument("--max-ideal-choices", type=int, default=300000)
    parser.add_argument("--max-raw-points", type=int, default=300000)
    parser.add_argument("--min-bucket-size", type=int, default=16)
    parser.add_argument("--min-translation-candidates", type=int, default=12)
    parser.add_argument("--top-buckets", type=int, default=8)
    parser.add_argument("--outdir", type=Path, default=Path("stage16_class_fiber_output"))
    parser.add_argument("--save-details", action="store_true")
    parser.add_argument("--plot-best", action="store_true")
    parser.add_argument("--max-plot-edges", type=int, default=30000)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(args.random_seed)

    polydisc_radii = parse_optional_float_list(args.polydisc_radii)
    principal_radii = parse_optional_float_list(args.principal_radii)

    global_summaries = []
    factor_summaries = []
    bucket_summaries = []
    translation_fiber_summaries = []

    best_summary = None
    best_context = None

    for m in args.m_values:
        for spc in args.split_prime_counts:
            print(f"Stage16 build: m={m}, split_prime_count={spc}")

            try:
                K, conj, embeddings, pair_blocks, metadata, factor_summary = build_split_prime_pairs(
                    m=m,
                    split_prime_count=spc,
                    verbose=args.verbose,
                )

                if metadata["ideal_choices"] > args.max_ideal_choices:
                    raise RuntimeError(
                        f"ideal choices {metadata['ideal_choices']} exceed --max-ideal-choices={args.max_ideal_choices}"
                    )

                products = enumerate_product_ideals(K, pair_blocks, args.max_ideal_choices)

                buckets, bucket_rows, cluster_stats = cluster_by_principal_ratios(
                    K=K,
                    products=products,
                    verbose=args.verbose,
                )

            except Exception as exc:
                print(f"  failed: {exc}")
                global_summaries.append(
                    {
                        "m": m,
                        "split_prime_count": spc,
                        "status": "failed",
                        "error": str(exc),
                    }
                )
                continue

            metadata.update(cluster_stats)

            for row in factor_summary:
                factor_summaries.append({**metadata, **row})

            for row in bucket_rows:
                bucket_summaries.append({**metadata, **row})

            buckets_sorted = sorted(buckets, key=lambda b: len(b["members"]), reverse=True)
            print(
                f"  products={len(products)}, buckets={len(buckets_sorted)}, "
                f"largest_bucket={len(buckets_sorted[0]['members']) if buckets_sorted else 0}, "
                f"ratio_tests={cluster_stats['principal_ratio_tests']}"
            )

            for bucket in buckets_sorted[: args.top_buckets]:
                bucket_size = len(bucket["members"])
                if bucket_size < args.min_bucket_size:
                    continue

                translation_rows = make_norm_one_translation_rows(K, conj, embeddings, bucket)
                candidate_count = len(translation_rows)

                translation_fiber_summaries.append(
                    {
                        **metadata,
                        "bucket_id": bucket["bucket_id"],
                        "bucket_size": bucket_size,
                        "candidate_norm_one_translations": candidate_count,
                    }
                )

                print(
                    f"  bucket={bucket['bucket_id']} size={bucket_size}, "
                    f"norm-one candidates={candidate_count}"
                )

                if candidate_count < args.min_translation_candidates:
                    continue

                for tc in args.translation_counts:
                    if tc > candidate_count:
                        continue

                    raw_points = 1 << tc
                    if raw_points > args.max_raw_points:
                        print(f"    skipping tc={tc}: 2^tc={raw_points} exceeds --max-raw-points")
                        continue

                    candidate_selections = []

                    if "angle" in args.selection_methods:
                        candidate_selections.append(("angle", 0, select_spread_by_angle(translation_rows, tc)))

                    if "random" in args.selection_methods and args.random_attempts > 0:
                        for attempt in range(1, args.random_attempts + 1):
                            candidate_selections.append(("random", attempt, select_random(translation_rows, tc, rng)))

                    for method, attempt, selected in candidate_selections:
                        for polyr in polydisc_radii:
                            for prinr in principal_radii:
                                summary, data = evaluate_selected(
                                    selected=selected,
                                    bucket_id=bucket["bucket_id"],
                                    bucket_size=bucket_size,
                                    candidate_translation_count=candidate_count,
                                    selection_method=method,
                                    selection_attempt=attempt,
                                    polydisc_radius=polyr,
                                    principal_radius=prinr,
                                    save_details=False,
                                )

                                if summary is None:
                                    continue

                                summary.update(metadata)
                                summary["status"] = "ok"
                                global_summaries.append(summary)

                                print(
                                    f"    tc={tc} {method}#{attempt} polyR={polyr} prinR={prinr}: "
                                    f"n={summary['distinct_points']} edges={summary['unit_distance_pairs']} "
                                    f"grid={summary['grid_unit_distance_pairs']} "
                                    f"ratio={summary['ratio_vs_grid']:.4f} "
                                    f"collisions={summary['exact_point_collisions']}"
                                )

                                if best_summary is None or (
                                    float(summary["ratio_vs_grid"]),
                                    int(summary["unit_distance_pairs"]),
                                ) > (
                                    float(best_summary["ratio_vs_grid"]),
                                    int(best_summary["unit_distance_pairs"]),
                                ):
                                    best_summary = summary
                                    best_context = (selected, bucket_size, candidate_count, polyr, prinr)

    # Write summary files.
    if global_summaries:
        fields = sorted({k for row in global_summaries for k in row.keys()})
        write_csv(args.outdir / "stage16_class_fiber_summary.csv", global_summaries, fields)
    else:
        write_csv(args.outdir / "stage16_class_fiber_summary.csv", [], ["status"])

    if factor_summaries:
        fields = sorted({k for row in factor_summaries for k in row.keys()})
        write_csv(args.outdir / "stage16_factor_summary.csv", factor_summaries, fields)
    else:
        write_csv(args.outdir / "stage16_factor_summary.csv", [], ["m"])

    if bucket_summaries:
        fields = sorted({k for row in bucket_summaries for k in row.keys()})
        write_csv(args.outdir / "stage16_bucket_summary.csv", bucket_summaries, fields)
    else:
        write_csv(args.outdir / "stage16_bucket_summary.csv", [], ["m"])

    if translation_fiber_summaries:
        fields = sorted({k for row in translation_fiber_summaries for k in row.keys()})
        write_csv(args.outdir / "stage16_translation_fiber_summary.csv", translation_fiber_summaries, fields)
    else:
        write_csv(args.outdir / "stage16_translation_fiber_summary.csv", [], ["m"])

    if best_summary is None:
        print("No successful evaluated class-fiber configuration.")
        print(f"Wrote: {args.outdir / 'stage16_class_fiber_summary.csv'}")
        print(f"Wrote: {args.outdir / 'stage16_factor_summary.csv'}")
        print(f"Wrote: {args.outdir / 'stage16_bucket_summary.csv'}")
        print(f"Wrote: {args.outdir / 'stage16_translation_fiber_summary.csv'}")
        return

    print()
    print("Best configuration:")
    for key, value in best_summary.items():
        text = str(value)
        if len(text) > 180:
            text = text[:180] + "..."
        print(f"{key}: {text}")

    if args.save_details or args.plot_best:
        selected, bucket_size, candidate_count, polyr, prinr = best_context

        summary, data = evaluate_selected(
            selected=selected,
            bucket_id=int(best_summary["bucket_id"]),
            bucket_size=bucket_size,
            candidate_translation_count=candidate_count,
            selection_method=str(best_summary["selection_method"]),
            selection_attempt=int(best_summary["selection_attempt"]),
            polydisc_radius=polyr,
            principal_radius=prinr,
            save_details=True,
        )
        summary.update(best_summary)

        stem = (
            f"best_m{best_summary['m']}"
            f"_spc{best_summary['split_prime_count']}"
            f"_bucket{best_summary['bucket_id']}"
            f"_tc{best_summary['selected_translations']}"
            f"_polyR{best_summary['polydisc_radius']}"
            f"_prinR{best_summary['principal_radius']}"
        ).replace(".", "p")

        if args.save_details:
            points_path = args.outdir / f"{stem}_points.csv"
            edges_path = args.outdir / f"{stem}_unit_edges.csv"
            selected_path = args.outdir / f"{stem}_selected_u.csv"

            write_csv(points_path, data["point_rows"], list(data["point_rows"][0].keys()))

            if data["edge_rows"]:
                write_csv(edges_path, data["edge_rows"], list(data["edge_rows"][0].keys()))
            else:
                write_csv(edges_path, [], ["from_id", "to_id"])

            selected_rows = []
            for i, row in enumerate(data["selected"]):
                selected_rows.append(
                    {
                        "id": i,
                        "u_key": row["u_key"],
                        "mask": row["mask"],
                        "angle": row["angle"],
                        "principal_abs": row["principal_abs"],
                        "max_abs_all_embeddings": row["max_abs_all_embeddings"],
                    }
                )
            write_csv(
                selected_path,
                selected_rows,
                ["id", "u_key", "mask", "angle", "principal_abs", "max_abs_all_embeddings"],
            )

            print(f"Wrote detail file: {points_path}")
            print(f"Wrote detail file: {edges_path}")
            print(f"Wrote detail file: {selected_path}")

        if args.plot_best:
            plot_path = args.outdir / f"{stem}_comparison.png"
            plot_result(
                output_png=plot_path,
                point_rows=data["point_rows"],
                edge_rows=data["edge_rows"],
                summary=summary,
                max_plot_edges=args.max_plot_edges,
            )
            print(f"Wrote plot: {plot_path}")

    print()
    print(f"Wrote: {args.outdir / 'stage16_class_fiber_summary.csv'}")
    print(f"Wrote: {args.outdir / 'stage16_factor_summary.csv'}")
    print(f"Wrote: {args.outdir / 'stage16_bucket_summary.csv'}")
    print(f"Wrote: {args.outdir / 'stage16_translation_fiber_summary.csv'}")


if __name__ == "__main__":
    main()
